language: python
python:
  - "2.7"
  - "3.4"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install pep8 --use-mirrors"
  - "pip install ."
before_script:
  - "pep8 --ignore=E501,E402 pouta_blueprints"
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
  - "python manage.py runserver -h localhost -p 8888 &"

# command to run tests
script:
  - nosetests
  - grunt travis-protractor

notifications:
  flowdock:
    secure: "VteCDhr47oT0S2kST2s755cYJMVZachfn+utiPAasqxTiaFb+ZpxB7jR9Dt6BTIyPTkxfVYGpfJv8+6sM72ezQNETu6XmwCatQvVIQ8S5jdSb5uW6jv+0bcZbyBfK+D6xzEG/yBjy6UZGdwhYDmf+aUd1RR1GAzl6BBDtvRP3Vk="
